export const ERROR_CODES = [
  'INVALID_TOKEN',
  'ACCESS_DENIED',
  'SCHEMA_INVALID',
  'SCHEMA_NOT_FOUND',
  'AUTH_UNAUTHENTICATED',
  'AUTH_FORBIDDEN',
  'ORG_SCOPE_FORBIDDEN',
  'SCENARIO_DRAFT_NOT_FOUND',
  'SCENARIO_INVALID_RELEASE',
  'PERSONA_PRESET_NOT_FOUND',
  'PERSONA_CONFIG_INVALID',
  'ASSIGNMENT_NOT_FOUND',
  'ASSIGNMENT_NOT_ELIGIBLE',
  'ASSIGNMENT_NOT_ACTIVE',
  'ASSIGNMENT_QUOTA_EXHAUSTED',
  'ASSIGNMENT_ILLEGAL_TRANSITION',
  'IDEMPOTENCY_KEY_REQUIRED',
  'ATTEMPT_ALREADY_ACTIVE',
  'SESSION_ALREADY_ACTIVE',
  'MESSAGE_IDEMPOTENCY_CONFLICT',
  'MESSAGE_SEQUENCE_CONFLICT',
  'CONVERSATION_NOT_FOUND',
  'CONVERSATION_CLOSED',
  'KNOWLEDGE_NOT_AVAILABLE',
  'MODEL_TIMEOUT',
  'MODEL_SCHEMA_INVALID',
  'MODEL_UPSTREAM_UNAVAILABLE',
  'EVALUATION_NOT_FOUND',
  'EVALUATION_REPORT_IMMUTABLE',
  'EVALUATION_RETRY_EXHAUSTED',
  'TEMPLATE_NOT_FOUND',
  'TEMPLATE_TITLE_CONFLICT',
  'FREE_SESSION_TEMPLATE_UNAVAILABLE',
  'LEARNER_PROFILE_NOT_FOUND',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export function isKnownErrorCode(value: string): value is ErrorCode {
  return (ERROR_CODES as readonly string[]).includes(value);
}
